name: 🚀 Deploy to cPanel FTP

on: 
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up LFTP
      run:  sudo apt-get install lftp

    - name: Install dependencies
      run: npm install
      
    - name: Build Next.js application
      run: npm run build
    
    - name: 📂 Deploy to cPanel FTP
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
    
